name: BuildDocuments
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor
    
    steps:
        
    - name: install git
      run: apk add --update git 
        
    - name: install asciidoctor
      run: gem install asciidoctor-pdf
      
    - name: checkout 
      uses: actions/checkout@main

    - name: build manuals
      run: |
        asciidoctor-pdf "User and Technical Manual.adoc"
        asciidoctor-pdf "upgrade instructions.adoc"
      working-directory: manual
    
    - name: move to generated-docs folder
      run: |
        mkdir -p generated-docs
        mv "manual/User and Technical Manual.pdf" generated-docs/
        mv "manual/upgrade instructions.pdf" generated-docs/
        
    - name: Git stuff
      run: |
        git config --global --add safe.directory $PWD
        git config --local user.email "gavin@aqualyd.nz"
        git config --local user.name "aqualyd-github-bot"
        git status
        git add "generated-docs/User and Technical Manual.pdf"
        git add "generated-docs/upgrade instructions.pdf"
        git commit --allow-empty -m "Push triggered asciidoc build"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
