name: BuildDocuments
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor
    
    steps:
        
    - name: install git
      run: apk add --update git 
        
    - name: install asciidoctor
      run: gem install asciidoctor-pdf
      
    - name: checkout 
      uses: actions/checkout@main

    - name: build User and Technical Manual.adoc
      run: asciidoctor-pdf "User and Technical Manual.adoc"
      working-directory: manual
    
    - name: Git stuff
      run: |
        git config --local user.email "gavin@aqualyd.nz"
        git config --local user.name "aqualyd-github-bot"
        git status
        git add "manual/User and Technical Manual.pdf"
        git commit --allow-empty -m "Push triggered asciidoc build"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
